<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LammRedis\Tests\ModuleTest'                               => __DIR__ . '/test/LammRedis/ModuleTest.php',
  'LammRedis\Tests\BaseModuleTest'                           => __DIR__ . '/test/LammRedis/BaseModuleTest.php',
  'LammRedis\Tests\PredisTest'                               => __DIR__ . '/test/LammRedis/src/PredisTest.php',
  'LammRedis\Tests\Factory\Service\PredisServiceFactoryTest' => __DIR__ . '/test/LammRedis/src/Factory/Service/PredisServiceFactoryTest.php',
  'LammRedis\Tests\Bootstrap'                                => __DIR__ . '/test/Bootstrap.php',
  'LammRedis\PredisClient'                                   => __DIR__ . '/src/LammRedis/PredisClient.php',
  'LammRedis\Factory\Service\PredisServiceFactory'           => __DIR__ . '/src/LammRedis/Factory/Service/PredisServiceFactory.php',
  'LammRedis\Module'                                         => __DIR__ . '/Module.php',
);
